export type Category = {
  name: string;
  count: number;
  active: boolean;
  image: string;
};

export type Product = {
  sku: string;
  name: string;
  category: string;
  qty: number;
  unit: string;
  price: number; // in KES
  status: "In-Stock" | "Low-Stock" | "Out-of-Stock";
  active: boolean;
  image: string;
};

export const categories: Category[] = [
  {
    name: "Fresh Produce",
    count: 7,
    active: true,
    image: "/products/fresh_produce/grape.png",
  },
  {
    name: "Ready To Cook",
    count: 4,
    active: true,
    image: "/products/ready_to_cook/beef_roast.png",
  },
  {
    name: "Seafood",
    count: 1,
    active: true,
    image: "/products/seafood/salmon_fillet.jpg",
  },
  {
    name: "Dairy & Eggs",
    count: 1,
    active: true,
    image: "/products/eggs/eggs.png",
  },
  {
    name: "Bakery",
    count: 1,
    active: true,
    image: "/products/bakery/buns.png",
  },
  {
    name: "Frozen Foods",
    count: 1,
    active: true,
    image: "/products/frozen_foods/macaroni.jpg",
  },
  {
    name: "Beverages",
    count: 1,
    active: false,
    image: "/products/beverages/pepsi.png",
  },
  {
    name: "Deli",
    count: 2,
    active: true,
    image: "/products/deli/pepperoni.png",
  },
];

export const products: Product[] = [
  {
    sku: "BKR-001",
    name: "Buns",
    category: "Bakery",
    qty: 45,
    unit: "pcs",
    price: 50,
    status: "In-Stock",
    active: true,
    image: "/products/bakery/buns.png",
  },
  {
    sku: "BEV-001",
    name: "Pepsi 500ml",
    category: "Beverages",
    qty: 8,
    unit: "bottles",
    price: 80,
    status: "Low-Stock",
    active: true,
    image: "/products/beverages/pepsi.png",
  },
  {
    sku: "DEL-001",
    name: "Pepperoni",
    category: "Deli",
    qty: 60,
    unit: "g",
    price: 350,
    status: "In-Stock",
    active: true,
    image: "/products/deli/pepperoni.png",
  },
  {
    sku: "DEL-002",
    name: "Tea Leaves",
    category: "Deli",
    qty: 0,
    unit: "g",
    price: 180,
    status: "Out-of-Stock",
    active: false,
    image: "/products/deli/tea.jpg",
  },
  {
    sku: "DAI-001",
    name: "Eggs (Tray)",
    category: "Dairy & Eggs",
    qty: 120,
    unit: "trays",
    price: 420,
    status: "In-Stock",
    active: true,
    image: "/products/eggs/eggs.png",
  },
  {
    sku: "FRP-001",
    name: "Avocado",
    category: "Fresh Produce",
    qty: 3,
    unit: "kg",
    price: 30,
    status: "Low-Stock",
    active: true,
    image: "/products/fresh_produce/avocado.jpg",
  },
  {
    sku: "FRP-002",
    name: "Cilantro",
    category: "Fresh Produce",
    qty: 0,
    unit: "bunch",
    price: 25,
    status: "Out-of-Stock",
    active: false,
    image: "/products/fresh_produce/cilantro.jpg",
  },
  {
    sku: "FRP-003",
    name: "Grapes",
    category: "Fresh Produce",
    qty: 90,
    unit: "kg",
    price: 150,
    status: "In-Stock",
    active: true,
    image: "/products/fresh_produce/grape.png",
  },
  {
    sku: "FRP-004",
    name: "Green Bell Pepper",
    category: "Fresh Produce",
    qty: 5,
    unit: "kg",
    price: 40,
    status: "Low-Stock",
    active: true,
    image: "/products/fresh_produce/green_bell_pepper.jpg",
  },
  {
    sku: "FRP-005",
    name: "Italian Blend",
    category: "Fresh Produce",
    qty: 32,
    unit: "pcs",
    price: 220,
    status: "In-Stock",
    active: true,
    image: "/products/fresh_produce/itallian_blend.png",
  },
  {
    sku: "FRP-006",
    name: "Lemon",
    category: "Fresh Produce",
    qty: 4,
    unit: "kg",
    price: 20,
    status: "Low-Stock",
    active: true,
    image: "/products/fresh_produce/lemon.jpg",
  },
  {
    sku: "FRP-007",
    name: "Lettuce",
    category: "Fresh Produce",
    qty: 0,
    unit: "head",
    price: 60,
    status: "Out-of-Stock",
    active: false,
    image: "/products/fresh_produce/lettuce.jpg",
  },
  {
    sku: "FRP-008",
    name: "Pineapple",
    category: "Fresh Produce",
    qty: 18,
    unit: "pcs",
    price: 110,
    status: "In-Stock",
    active: true,
    image: "/products/fresh_produce/pinaepple.jpg",
  },
  {
    sku: "FRZ-001",
    name: "Macaroni",
    category: "Frozen Foods",
    qty: 70,
    unit: "packs",
    price: 95,
    status: "In-Stock",
    active: true,
    image: "/products/frozen_foods/macaroni.jpg",
  },
  {
    sku: "RTC-001",
    name: "Beef Roast",
    category: "Ready To Cook",
    qty: 22,
    unit: "kg",
    price: 850,
    status: "In-Stock",
    active: true,
    image: "/products/ready_to_cook/beef_roast.png",
  },
  {
    sku: "RTC-002",
    name: "Lemon Thyme Salmon",
    category: "Ready To Cook",
    qty: 6,
    unit: "pcs",
    price: 1200,
    status: "Low-Stock",
    active: true,
    image: "/products/ready_to_cook/lemon_thyme_salmon.png",
  },
  {
    sku: "RTC-003",
    name: "Pepper Jack Cheese",
    category: "Ready To Cook",
    qty: 0,
    unit: "pcs",
    price: 480,
    status: "Out-of-Stock",
    active: false,
    image: "/products/ready_to_cook/pepper_jack_cheese.png",
  },
  {
    sku: "RTC-004",
    name: "Pork Roast",
    category: "Ready To Cook",
    qty: 14,
    unit: "kg",
    price: 750,
    status: "In-Stock",
    active: true,
    image: "/products/ready_to_cook/pork_roast.png",
  },
  {
    sku: "SEA-001",
    name: "Salmon Fillet",
    category: "Seafood",
    qty: 9,
    unit: "pcs",
    price: 950,
    status: "In-Stock",
    active: true,
    image: "/products/seafood/salmon_fillet.jpg",
  },
];
